"""Bootstrap secrets for managed installs and first process start.

Writes ``$TOMO_HOME/.env`` (``TOMO_SESSION_SECRET``, ``TOMO_ADMIN_PASSWORD``)
and ``.secret_key`` when missing. Never overwrites existing values. Newly
generated keys are also injected into ``os.environ`` so the current process
picks them up without a restart.
"""

from __future__ import annotations

import os
import secrets
from dataclasses import dataclass, field
from pathlib import Path

from cryptography.fernet import Fernet

from app.core import config


@dataclass
class BootstrapResult:
    """What was created this call (empty strings when already present)."""

    env_path: Path
    secret_key_path: Path
    created_session_secret: bool = False
    created_admin_password: bool = False
    created_secret_key: bool = False
    # Only set when we generated it this call (for install UX).
    admin_password: str = ""
    notes: list[str] = field(default_factory=list)


def _env_has_key(env_file: Path, key: str) -> bool:
    if not env_file.is_file():
        return False
    try:
        text = env_file.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return False
    prefix = f"{key}="
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("#") or not s:
            continue
        if s.startswith(prefix) or s.startswith(f"{key} ="):
            return True
    return False


def _append_env(env_file: Path, key: str, value: str, comment: str) -> None:
    env_file.parent.mkdir(parents=True, exist_ok=True)
    if not env_file.exists():
        env_file.touch()
        try:
            os.chmod(env_file, 0o600)
        except OSError:
            pass
    with env_file.open("a", encoding="utf-8") as fh:
        fh.write(f"\n# {comment}\n")
        fh.write(f"{key}={value}\n")
    try:
        os.chmod(env_file, 0o600)
    except OSError:
        pass


def ensure_bootstrap_secrets(root: Path | None = None) -> BootstrapResult:
    """Ensure session/admin/.secret_key exist under *root* (default ``$TOMO_HOME``).

    Idempotent. Process env already set wins (no file write for that key).
    Newly generated values are written to ``.env`` / ``.secret_key`` and set in
    ``os.environ`` for the current process.
    """
    home_root = Path(root) if root is not None else config.TOMO_HOME
    home_root.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(home_root, 0o700)
    except OSError:
        pass

    env_file = home_root / ".env"
    sk_path = home_root / ".secret_key"
    result = BootstrapResult(env_path=env_file, secret_key_path=sk_path)

    # --- session cookie signing ---
    if (os.environ.get("TOMO_SESSION_SECRET") or "").strip():
        result.notes.append("TOMO_SESSION_SECRET already set in environment")
    elif _env_has_key(env_file, "TOMO_SESSION_SECRET"):
        result.notes.append(f"TOMO_SESSION_SECRET already set in {env_file}")
    else:
        value = secrets.token_urlsafe(32)
        _append_env(
            env_file,
            "TOMO_SESSION_SECRET",
            value,
            "Generated by Tomo bootstrap — cookie signing secret (do not commit)",
        )
        os.environ["TOMO_SESSION_SECRET"] = value
        result.created_session_secret = True
        result.notes.append(f"Generated TOMO_SESSION_SECRET in {env_file}")

    # --- bootstrap admin password (seed-only when users table empty) ---
    if (os.environ.get("TOMO_ADMIN_PASSWORD") or "").strip():
        result.notes.append("TOMO_ADMIN_PASSWORD already set in environment")
    elif _env_has_key(env_file, "TOMO_ADMIN_PASSWORD"):
        result.notes.append(f"TOMO_ADMIN_PASSWORD already set in {env_file}")
    else:
        value = secrets.token_urlsafe(18)
        _append_env(
            env_file,
            "TOMO_ADMIN_PASSWORD",
            value,
            "Generated by Tomo bootstrap — first-login admin password (do not commit)",
        )
        os.environ["TOMO_ADMIN_PASSWORD"] = value
        result.created_admin_password = True
        result.admin_password = value
        result.notes.append(f"Generated TOMO_ADMIN_PASSWORD in {env_file}")

    # --- at-rest Fernet master key ---
    if (os.environ.get("TOMO_SECRET_KEY") or "").strip():
        result.notes.append("TOMO_SECRET_KEY set in environment; skipping .secret_key")
    elif sk_path.is_file():
        result.notes.append(f".secret_key already present at {sk_path}")
    else:
        sk_path.write_bytes(Fernet.generate_key())
        try:
            os.chmod(sk_path, 0o600)
        except OSError:
            pass
        result.created_secret_key = True
        result.notes.append(f"Generated {sk_path}")

    return result


def apply_bootstrap_to_config() -> None:
    """Refresh in-process config secrets from ``os.environ`` after bootstrap.

    Config module binds ``SESSION_SECRET`` / ``ADMIN_PASSWORD`` at import time.
    After :func:`ensure_bootstrap_secrets` injects env vars, call this so the
    running process (and :func:`assert_bind_safety`) sees the new values.
    """
    session = (os.environ.get("TOMO_SESSION_SECRET") or "").strip()
    if session:
        config.SESSION_SECRET = session
    admin = (os.environ.get("TOMO_ADMIN_PASSWORD") or "").strip()
    if admin:
        config.ADMIN_PASSWORD = admin


__all__ = [
    "BootstrapResult",
    "ensure_bootstrap_secrets",
    "apply_bootstrap_to_config",
]
